{% set name = "pangeo-forge-recipes" %}
{% set version = "0.10.6" %}
{% set hash_val = "14bb684993208c2f3b23e62837fa6870f8c27720c264292a1e8db6af513192eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm[toml] >=6.0
  run:
    - dask-core >=2021.11.2
    - fsspec >=2023.4.0
    - python >=3.8
    - apache-beam
    - cftime
    - fastparquet
    - fsspec[http] >=2023.4.0
    - kerchunk >=0.0.7
    - ujson
    - h5py >=3.3.0
    - numcodecs >=0.9.0
    - xarray >=0.18.0
    - zarr >=2.12.0
    - netcdf4
    - h5netcdf
    - dask >=2021.11.2

test:
  imports:
    - pangeo_forge_recipes
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pangeo-forge.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Python library for building Pangeo Forge recipes.
  description: |
    Pangeo Forge is an open source platform for data Extraction, Transformation, 
    and Loading (ETL). The goal of Pangeo Forge is to make it easy to extract data 
    from traditional data repositories and deposit in cloud object storage in 
    analysis-ready, cloud-optimized (ARCO) format. Pangeo Forge is inspired directly 
    by Conda Forge, a community-led collection of recipes for building conda packages. 
    We hope that Pangeo Forge can play the same role for datasets.
  doc_url: https://pangeo-forge.readthedocs.io/en/latest/
  dev_url: https://github.com/pangeo-forge/pangeo-forge-recipes

extra:
  recipe-maintainers:
    - alxmrs
    - andersy005
    - cisaacstern
    - rabernat
    - yuvipanda
